# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
    #branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DBT_GOOGLE_BIGQUERY_KEYFILE_PROD: ../dbt-service-account.json
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install DBT
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core==1.0.0
          pip install dbt-bigquery
          pip install sqlfluff
      
      - name: Authenticate using service account
        run: |
          echo "$KEYFILE" > ./dbt-service-account.json
          cd dbt_demo
          dbt debug --profiles-dir  ${{ secrets.DBT_PROFILES_DIR }}
          dbt deps --profiles-dir  ${{ secrets.DBT_PROFILES_DIR }}
          dbt run --profiles-dir  ${{ secrets.DBT_PROFILES_DIR }}
        shell: bash
        env:
          KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE_PROD}}
      - name: find prof dir
        run: |
         ls dbt_demo
         echo $GITHUB_WORKSPACE
         ls $GITHUB_WORKSPACE
         echo ${{ secrets.DBT_PROFILES_DIR }}
      - name: Upload README.md to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: dbt_demo/target/manifest.json
          credentials: ${{secrets.GDRIVE_CRED_BASE64}}
          folder: ${{secrets.DRIVE_FOLDER_ID}}
          
      - name: Download Manifest
        run: |
          pip install google-api-python-client
          pip install ZDrive
          python gdrive_downloader.py
          ls ./
        

  
